# Generated by Django 2.1.8 on 2019-07-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_image',
            new_name='goods_image',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_price',
            new_name='goods_price',
        ),
    ]
